// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQWW9A8o6nWpUmhWMhxBGUp_2v0sVprMg',
    appId: '1:317665390621:web:817cc71288a692f46e56f4',
    messagingSenderId: '317665390621',
    projectId: 'mailboxpush-ec9c0',
    authDomain: 'mailboxpush-ec9c0.firebaseapp.com',
    storageBucket: 'mailboxpush-ec9c0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiQNQtlVO3u02mSlnpiguCJZ7GCXyX7fU',
    appId: '1:317665390621:android:6162ec060dbc8c2d6e56f4',
    messagingSenderId: '317665390621',
    projectId: 'mailboxpush-ec9c0',
    storageBucket: 'mailboxpush-ec9c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrRPxQk73SnWIOHqmUsYkmNVzcfwjNT9I',
    appId: '1:317665390621:ios:f246bff0e10e57c86e56f4',
    messagingSenderId: '317665390621',
    projectId: 'mailboxpush-ec9c0',
    storageBucket: 'mailboxpush-ec9c0.firebasestorage.app',
    iosBundleId: 'com.example.mailboxappProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrRPxQk73SnWIOHqmUsYkmNVzcfwjNT9I',
    appId: '1:317665390621:ios:f246bff0e10e57c86e56f4',
    messagingSenderId: '317665390621',
    projectId: 'mailboxpush-ec9c0',
    storageBucket: 'mailboxpush-ec9c0.firebasestorage.app',
    iosBundleId: 'com.example.mailboxappProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQWW9A8o6nWpUmhWMhxBGUp_2v0sVprMg',
    appId: '1:317665390621:web:2d8aab7e2390e52c6e56f4',
    messagingSenderId: '317665390621',
    projectId: 'mailboxpush-ec9c0',
    authDomain: 'mailboxpush-ec9c0.firebaseapp.com',
    storageBucket: 'mailboxpush-ec9c0.firebasestorage.app',
  );
}
